apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-blue
  name: nginx-blue-svc
  #resourceVersion: "20986"
  #uid: d66a9321-610c-4a0d-9a5b-8b98a167a1c4
spec:
  clusterIP: 10.233.35.188
  clusterIPs:
  - 10.233.35.188
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-blue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-green
  name: nginx-green-svc
  #resourceVersion: "21321"
  #uid: bbcce65d-3357-49a5-8f7f-9e364fa5322f
spec:
  clusterIP: 10.233.14.208
  clusterIPs:
  - 10.233.14.208
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-green
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---

